#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1026
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="LifeCycle")]
	public partial class LifeCycleDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertContact(Contact instance);
    partial void UpdateContact(Contact instance);
    partial void DeleteContact(Contact instance);
    #endregion
		
		public LifeCycleDBDataContext() : 
				base(global::BE.Properties.Settings.Default.LifeCycleConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public LifeCycleDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LifeCycleDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LifeCycleDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LifeCycleDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Contact> Contacts
		{
			get
			{
				return this.GetTable<Contact>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Contact")]
	public partial class Contact : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ContactId;
		
		private string _cntFirstName;
		
		private string _cntLastName;
		
		private string _cntAlsoKnownAs;
		
		private string _cntFacility;
		
		private bool _cntActive;
		
		private string _cntLanguage;
		
		private string _cntCode1;
		
		private string _cntCode2;
		
		private System.Nullable<short> _cntContactType;
		
		private bool _cntValid;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnContactIdChanging(int value);
    partial void OnContactIdChanged();
    partial void OncntFirstNameChanging(string value);
    partial void OncntFirstNameChanged();
    partial void OncntLastNameChanging(string value);
    partial void OncntLastNameChanged();
    partial void OncntAlsoKnownAsChanging(string value);
    partial void OncntAlsoKnownAsChanged();
    partial void OncntFacilityChanging(string value);
    partial void OncntFacilityChanged();
    partial void OncntActiveChanging(bool value);
    partial void OncntActiveChanged();
    partial void OncntLanguageChanging(string value);
    partial void OncntLanguageChanged();
    partial void OncntCode1Changing(string value);
    partial void OncntCode1Changed();
    partial void OncntCode2Changing(string value);
    partial void OncntCode2Changed();
    partial void OncntContactTypeChanging(System.Nullable<short> value);
    partial void OncntContactTypeChanged();
    partial void OncntValidChanging(bool value);
    partial void OncntValidChanged();
    #endregion
		
		public Contact()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ContactId
		{
			get
			{
				return this._ContactId;
			}
			set
			{
				if ((this._ContactId != value))
				{
					this.OnContactIdChanging(value);
					this.SendPropertyChanging();
					this._ContactId = value;
					this.SendPropertyChanged("ContactId");
					this.OnContactIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cntFirstName", DbType="NVarChar(64)")]
		public string cntFirstName
		{
			get
			{
				return this._cntFirstName;
			}
			set
			{
				if ((this._cntFirstName != value))
				{
					this.OncntFirstNameChanging(value);
					this.SendPropertyChanging();
					this._cntFirstName = value;
					this.SendPropertyChanged("cntFirstName");
					this.OncntFirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cntLastName", DbType="NVarChar(64)")]
		public string cntLastName
		{
			get
			{
				return this._cntLastName;
			}
			set
			{
				if ((this._cntLastName != value))
				{
					this.OncntLastNameChanging(value);
					this.SendPropertyChanging();
					this._cntLastName = value;
					this.SendPropertyChanged("cntLastName");
					this.OncntLastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cntAlsoKnownAs", DbType="NVarChar(64)")]
		public string cntAlsoKnownAs
		{
			get
			{
				return this._cntAlsoKnownAs;
			}
			set
			{
				if ((this._cntAlsoKnownAs != value))
				{
					this.OncntAlsoKnownAsChanging(value);
					this.SendPropertyChanging();
					this._cntAlsoKnownAs = value;
					this.SendPropertyChanged("cntAlsoKnownAs");
					this.OncntAlsoKnownAsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cntFacility", DbType="NVarChar(64)")]
		public string cntFacility
		{
			get
			{
				return this._cntFacility;
			}
			set
			{
				if ((this._cntFacility != value))
				{
					this.OncntFacilityChanging(value);
					this.SendPropertyChanging();
					this._cntFacility = value;
					this.SendPropertyChanged("cntFacility");
					this.OncntFacilityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cntActive", DbType="Bit NOT NULL")]
		public bool cntActive
		{
			get
			{
				return this._cntActive;
			}
			set
			{
				if ((this._cntActive != value))
				{
					this.OncntActiveChanging(value);
					this.SendPropertyChanging();
					this._cntActive = value;
					this.SendPropertyChanged("cntActive");
					this.OncntActiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cntLanguage", DbType="NVarChar(32)")]
		public string cntLanguage
		{
			get
			{
				return this._cntLanguage;
			}
			set
			{
				if ((this._cntLanguage != value))
				{
					this.OncntLanguageChanging(value);
					this.SendPropertyChanging();
					this._cntLanguage = value;
					this.SendPropertyChanged("cntLanguage");
					this.OncntLanguageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cntCode1", DbType="NVarChar(32)")]
		public string cntCode1
		{
			get
			{
				return this._cntCode1;
			}
			set
			{
				if ((this._cntCode1 != value))
				{
					this.OncntCode1Changing(value);
					this.SendPropertyChanging();
					this._cntCode1 = value;
					this.SendPropertyChanged("cntCode1");
					this.OncntCode1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cntCode2", DbType="NVarChar(32)")]
		public string cntCode2
		{
			get
			{
				return this._cntCode2;
			}
			set
			{
				if ((this._cntCode2 != value))
				{
					this.OncntCode2Changing(value);
					this.SendPropertyChanging();
					this._cntCode2 = value;
					this.SendPropertyChanged("cntCode2");
					this.OncntCode2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cntContactType", DbType="SmallInt")]
		public System.Nullable<short> cntContactType
		{
			get
			{
				return this._cntContactType;
			}
			set
			{
				if ((this._cntContactType != value))
				{
					this.OncntContactTypeChanging(value);
					this.SendPropertyChanging();
					this._cntContactType = value;
					this.SendPropertyChanged("cntContactType");
					this.OncntContactTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cntValid", DbType="Bit NOT NULL")]
		public bool cntValid
		{
			get
			{
				return this._cntValid;
			}
			set
			{
				if ((this._cntValid != value))
				{
					this.OncntValidChanging(value);
					this.SendPropertyChanging();
					this._cntValid = value;
					this.SendPropertyChanged("cntValid");
					this.OncntValidChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
