#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1026
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="TamiLife")]
	public partial class TamiLifeDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertParametroGeneral(ParametroGeneral instance);
    partial void UpdateParametroGeneral(ParametroGeneral instance);
    partial void DeleteParametroGeneral(ParametroGeneral instance);
    partial void InsertTipoEstablecimiento(TipoEstablecimiento instance);
    partial void UpdateTipoEstablecimiento(TipoEstablecimiento instance);
    partial void DeleteTipoEstablecimiento(TipoEstablecimiento instance);
    partial void InsertEstablecimiento(Establecimiento instance);
    partial void UpdateEstablecimiento(Establecimiento instance);
    partial void DeleteEstablecimiento(Establecimiento instance);
    partial void InsertEnvio(Envio instance);
    partial void UpdateEnvio(Envio instance);
    partial void DeleteEnvio(Envio instance);
    partial void InsertTarjeta(Tarjeta instance);
    partial void UpdateTarjeta(Tarjeta instance);
    partial void DeleteTarjeta(Tarjeta instance);
    partial void InsertUbigeo(Ubigeo instance);
    partial void UpdateUbigeo(Ubigeo instance);
    partial void DeleteUbigeo(Ubigeo instance);
    partial void InsertRecepcion(Recepcion instance);
    partial void UpdateRecepcion(Recepcion instance);
    partial void DeleteRecepcion(Recepcion instance);
    partial void InsertPrueba(Prueba instance);
    partial void UpdatePrueba(Prueba instance);
    partial void DeletePrueba(Prueba instance);
    #endregion
		
		public TamiLifeDBDataContext() : 
				base(global::BE.Properties.Settings.Default.TamiLifeConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public TamiLifeDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TamiLifeDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TamiLifeDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TamiLifeDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ParametroGeneral> ParametroGenerals
		{
			get
			{
				return this.GetTable<ParametroGeneral>();
			}
		}
		
		public System.Data.Linq.Table<TipoEstablecimiento> TipoEstablecimientos
		{
			get
			{
				return this.GetTable<TipoEstablecimiento>();
			}
		}
		
		public System.Data.Linq.Table<Establecimiento> Establecimientos
		{
			get
			{
				return this.GetTable<Establecimiento>();
			}
		}
		
		public System.Data.Linq.Table<Envio> Envios
		{
			get
			{
				return this.GetTable<Envio>();
			}
		}
		
		public System.Data.Linq.Table<Tarjeta> Tarjetas
		{
			get
			{
				return this.GetTable<Tarjeta>();
			}
		}
		
		public System.Data.Linq.Table<Ubigeo> Ubigeos
		{
			get
			{
				return this.GetTable<Ubigeo>();
			}
		}
		
		public System.Data.Linq.Table<Recepcion> Recepcions
		{
			get
			{
				return this.GetTable<Recepcion>();
			}
		}
		
		public System.Data.Linq.Table<Rango> Rangos
		{
			get
			{
				return this.GetTable<Rango>();
			}
		}
		
		public System.Data.Linq.Table<Prueba> Pruebas
		{
			get
			{
				return this.GetTable<Prueba>();
			}
		}
		
		public System.Data.Linq.Table<Vista_ListaTarjeta> Vista_ListaTarjetas
		{
			get
			{
				return this.GetTable<Vista_ListaTarjeta>();
			}
		}
		
		public System.Data.Linq.Table<Vista_ListaRecepcione> Vista_ListaRecepciones
		{
			get
			{
				return this.GetTable<Vista_ListaRecepcione>();
			}
		}
		
		public System.Data.Linq.Table<Vista_ListaEnvio> Vista_ListaEnvios
		{
			get
			{
				return this.GetTable<Vista_ListaEnvio>();
			}
		}
		
		public System.Data.Linq.Table<Vista_Establecimiento> Vista_Establecimientos
		{
			get
			{
				return this.GetTable<Vista_Establecimiento>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ParametroGeneral")]
	public partial class ParametroGeneral : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idParametroGeneral;
		
		private string _ValorTexto;
		
		private System.Nullable<int> _ValorEntero;
		
		private System.Nullable<float> _ValorReal;
		
		private System.Nullable<int> _Grupo;
		
		private System.Nullable<int> _SubGrupo;
		
		private System.Nullable<int> _Estado;
		
		private string _Nombre;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidParametroGeneralChanging(int value);
    partial void OnidParametroGeneralChanged();
    partial void OnValorTextoChanging(string value);
    partial void OnValorTextoChanged();
    partial void OnValorEnteroChanging(System.Nullable<int> value);
    partial void OnValorEnteroChanged();
    partial void OnValorRealChanging(System.Nullable<float> value);
    partial void OnValorRealChanged();
    partial void OnGrupoChanging(System.Nullable<int> value);
    partial void OnGrupoChanged();
    partial void OnSubGrupoChanging(System.Nullable<int> value);
    partial void OnSubGrupoChanged();
    partial void OnEstadoChanging(System.Nullable<int> value);
    partial void OnEstadoChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    #endregion
		
		public ParametroGeneral()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idParametroGeneral", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idParametroGeneral
		{
			get
			{
				return this._idParametroGeneral;
			}
			set
			{
				if ((this._idParametroGeneral != value))
				{
					this.OnidParametroGeneralChanging(value);
					this.SendPropertyChanging();
					this._idParametroGeneral = value;
					this.SendPropertyChanged("idParametroGeneral");
					this.OnidParametroGeneralChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ValorTexto", DbType="NVarChar(300)")]
		public string ValorTexto
		{
			get
			{
				return this._ValorTexto;
			}
			set
			{
				if ((this._ValorTexto != value))
				{
					this.OnValorTextoChanging(value);
					this.SendPropertyChanging();
					this._ValorTexto = value;
					this.SendPropertyChanged("ValorTexto");
					this.OnValorTextoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ValorEntero", DbType="Int")]
		public System.Nullable<int> ValorEntero
		{
			get
			{
				return this._ValorEntero;
			}
			set
			{
				if ((this._ValorEntero != value))
				{
					this.OnValorEnteroChanging(value);
					this.SendPropertyChanging();
					this._ValorEntero = value;
					this.SendPropertyChanged("ValorEntero");
					this.OnValorEnteroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ValorReal", DbType="Real")]
		public System.Nullable<float> ValorReal
		{
			get
			{
				return this._ValorReal;
			}
			set
			{
				if ((this._ValorReal != value))
				{
					this.OnValorRealChanging(value);
					this.SendPropertyChanging();
					this._ValorReal = value;
					this.SendPropertyChanged("ValorReal");
					this.OnValorRealChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Grupo", DbType="Int")]
		public System.Nullable<int> Grupo
		{
			get
			{
				return this._Grupo;
			}
			set
			{
				if ((this._Grupo != value))
				{
					this.OnGrupoChanging(value);
					this.SendPropertyChanging();
					this._Grupo = value;
					this.SendPropertyChanged("Grupo");
					this.OnGrupoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubGrupo", DbType="Int")]
		public System.Nullable<int> SubGrupo
		{
			get
			{
				return this._SubGrupo;
			}
			set
			{
				if ((this._SubGrupo != value))
				{
					this.OnSubGrupoChanging(value);
					this.SendPropertyChanging();
					this._SubGrupo = value;
					this.SendPropertyChanged("SubGrupo");
					this.OnSubGrupoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="Int")]
		public System.Nullable<int> Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this.OnEstadoChanging(value);
					this.SendPropertyChanging();
					this._Estado = value;
					this.SendPropertyChanged("Estado");
					this.OnEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NVarChar(100)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TipoEstablecimiento")]
	public partial class TipoEstablecimiento : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idTipoEstablecimiento;
		
		private string _Nombre;
		
		private int _Estado;
		
		private EntitySet<Establecimiento> _Establecimientos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidTipoEstablecimientoChanging(int value);
    partial void OnidTipoEstablecimientoChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnEstadoChanging(int value);
    partial void OnEstadoChanged();
    #endregion
		
		public TipoEstablecimiento()
		{
			this._Establecimientos = new EntitySet<Establecimiento>(new Action<Establecimiento>(this.attach_Establecimientos), new Action<Establecimiento>(this.detach_Establecimientos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idTipoEstablecimiento", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idTipoEstablecimiento
		{
			get
			{
				return this._idTipoEstablecimiento;
			}
			set
			{
				if ((this._idTipoEstablecimiento != value))
				{
					this.OnidTipoEstablecimientoChanging(value);
					this.SendPropertyChanging();
					this._idTipoEstablecimiento = value;
					this.SendPropertyChanged("idTipoEstablecimiento");
					this.OnidTipoEstablecimientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="Int NOT NULL")]
		public int Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this.OnEstadoChanging(value);
					this.SendPropertyChanging();
					this._Estado = value;
					this.SendPropertyChanged("Estado");
					this.OnEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TipoEstablecimiento_Establecimiento", Storage="_Establecimientos", ThisKey="idTipoEstablecimiento", OtherKey="idTipoEstablecimiento")]
		public EntitySet<Establecimiento> Establecimientos
		{
			get
			{
				return this._Establecimientos;
			}
			set
			{
				this._Establecimientos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Establecimientos(Establecimiento entity)
		{
			this.SendPropertyChanging();
			entity.TipoEstablecimiento = this;
		}
		
		private void detach_Establecimientos(Establecimiento entity)
		{
			this.SendPropertyChanging();
			entity.TipoEstablecimiento = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Establecimiento")]
	public partial class Establecimiento : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idEstablecimiento;
		
		private int _idTipoEstablecimiento;
		
		private string _Nombre;
		
		private string _Direccion;
		
		private string _Telefono1;
		
		private string _Telefono2;
		
		private System.Nullable<int> _Departamento;
		
		private System.Nullable<int> _Provincia;
		
		private System.Nullable<int> _Distrito;
		
		private int _Estado;
		
		private string _Codigo;
		
		private string _CodRenaes;
		
		private EntitySet<Envio> _Envios;
		
		private EntitySet<Tarjeta> _Tarjetas;
		
		private EntitySet<Recepcion> _Recepcions;
		
		private EntityRef<TipoEstablecimiento> _TipoEstablecimiento;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidEstablecimientoChanging(int value);
    partial void OnidEstablecimientoChanged();
    partial void OnidTipoEstablecimientoChanging(int value);
    partial void OnidTipoEstablecimientoChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnDireccionChanging(string value);
    partial void OnDireccionChanged();
    partial void OnTelefono1Changing(string value);
    partial void OnTelefono1Changed();
    partial void OnTelefono2Changing(string value);
    partial void OnTelefono2Changed();
    partial void OnDepartamentoChanging(System.Nullable<int> value);
    partial void OnDepartamentoChanged();
    partial void OnProvinciaChanging(System.Nullable<int> value);
    partial void OnProvinciaChanged();
    partial void OnDistritoChanging(System.Nullable<int> value);
    partial void OnDistritoChanged();
    partial void OnEstadoChanging(int value);
    partial void OnEstadoChanged();
    partial void OnCodigoChanging(string value);
    partial void OnCodigoChanged();
    partial void OnCodRenaesChanging(string value);
    partial void OnCodRenaesChanged();
    #endregion
		
		public Establecimiento()
		{
			this._Envios = new EntitySet<Envio>(new Action<Envio>(this.attach_Envios), new Action<Envio>(this.detach_Envios));
			this._Tarjetas = new EntitySet<Tarjeta>(new Action<Tarjeta>(this.attach_Tarjetas), new Action<Tarjeta>(this.detach_Tarjetas));
			this._Recepcions = new EntitySet<Recepcion>(new Action<Recepcion>(this.attach_Recepcions), new Action<Recepcion>(this.detach_Recepcions));
			this._TipoEstablecimiento = default(EntityRef<TipoEstablecimiento>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idEstablecimiento", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idEstablecimiento
		{
			get
			{
				return this._idEstablecimiento;
			}
			set
			{
				if ((this._idEstablecimiento != value))
				{
					this.OnidEstablecimientoChanging(value);
					this.SendPropertyChanging();
					this._idEstablecimiento = value;
					this.SendPropertyChanged("idEstablecimiento");
					this.OnidEstablecimientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idTipoEstablecimiento", DbType="Int NOT NULL")]
		public int idTipoEstablecimiento
		{
			get
			{
				return this._idTipoEstablecimiento;
			}
			set
			{
				if ((this._idTipoEstablecimiento != value))
				{
					if (this._TipoEstablecimiento.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidTipoEstablecimientoChanging(value);
					this.SendPropertyChanging();
					this._idTipoEstablecimiento = value;
					this.SendPropertyChanged("idTipoEstablecimiento");
					this.OnidTipoEstablecimientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NVarChar(64)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="NVarChar(40)")]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this.OnDireccionChanging(value);
					this.SendPropertyChanging();
					this._Direccion = value;
					this.SendPropertyChanged("Direccion");
					this.OnDireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono1", DbType="NVarChar(15)")]
		public string Telefono1
		{
			get
			{
				return this._Telefono1;
			}
			set
			{
				if ((this._Telefono1 != value))
				{
					this.OnTelefono1Changing(value);
					this.SendPropertyChanging();
					this._Telefono1 = value;
					this.SendPropertyChanged("Telefono1");
					this.OnTelefono1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono2", DbType="NVarChar(15)")]
		public string Telefono2
		{
			get
			{
				return this._Telefono2;
			}
			set
			{
				if ((this._Telefono2 != value))
				{
					this.OnTelefono2Changing(value);
					this.SendPropertyChanging();
					this._Telefono2 = value;
					this.SendPropertyChanged("Telefono2");
					this.OnTelefono2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Departamento", DbType="Int")]
		public System.Nullable<int> Departamento
		{
			get
			{
				return this._Departamento;
			}
			set
			{
				if ((this._Departamento != value))
				{
					this.OnDepartamentoChanging(value);
					this.SendPropertyChanging();
					this._Departamento = value;
					this.SendPropertyChanged("Departamento");
					this.OnDepartamentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Provincia", DbType="Int")]
		public System.Nullable<int> Provincia
		{
			get
			{
				return this._Provincia;
			}
			set
			{
				if ((this._Provincia != value))
				{
					this.OnProvinciaChanging(value);
					this.SendPropertyChanging();
					this._Provincia = value;
					this.SendPropertyChanged("Provincia");
					this.OnProvinciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Distrito", DbType="Int")]
		public System.Nullable<int> Distrito
		{
			get
			{
				return this._Distrito;
			}
			set
			{
				if ((this._Distrito != value))
				{
					this.OnDistritoChanging(value);
					this.SendPropertyChanging();
					this._Distrito = value;
					this.SendPropertyChanged("Distrito");
					this.OnDistritoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="Int NOT NULL")]
		public int Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this.OnEstadoChanging(value);
					this.SendPropertyChanging();
					this._Estado = value;
					this.SendPropertyChanged("Estado");
					this.OnEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Codigo", DbType="NVarChar(32)")]
		public string Codigo
		{
			get
			{
				return this._Codigo;
			}
			set
			{
				if ((this._Codigo != value))
				{
					this.OnCodigoChanging(value);
					this.SendPropertyChanging();
					this._Codigo = value;
					this.SendPropertyChanged("Codigo");
					this.OnCodigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodRenaes", DbType="NVarChar(20)")]
		public string CodRenaes
		{
			get
			{
				return this._CodRenaes;
			}
			set
			{
				if ((this._CodRenaes != value))
				{
					this.OnCodRenaesChanging(value);
					this.SendPropertyChanging();
					this._CodRenaes = value;
					this.SendPropertyChanged("CodRenaes");
					this.OnCodRenaesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Establecimiento_Envio", Storage="_Envios", ThisKey="idEstablecimiento", OtherKey="idEstablecimiento")]
		public EntitySet<Envio> Envios
		{
			get
			{
				return this._Envios;
			}
			set
			{
				this._Envios.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Establecimiento_Tarjeta", Storage="_Tarjetas", ThisKey="idEstablecimiento", OtherKey="idEstablecimiento")]
		public EntitySet<Tarjeta> Tarjetas
		{
			get
			{
				return this._Tarjetas;
			}
			set
			{
				this._Tarjetas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Establecimiento_Recepcion", Storage="_Recepcions", ThisKey="idEstablecimiento", OtherKey="idEstablecimiento")]
		public EntitySet<Recepcion> Recepcions
		{
			get
			{
				return this._Recepcions;
			}
			set
			{
				this._Recepcions.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TipoEstablecimiento_Establecimiento", Storage="_TipoEstablecimiento", ThisKey="idTipoEstablecimiento", OtherKey="idTipoEstablecimiento", IsForeignKey=true)]
		public TipoEstablecimiento TipoEstablecimiento
		{
			get
			{
				return this._TipoEstablecimiento.Entity;
			}
			set
			{
				TipoEstablecimiento previousValue = this._TipoEstablecimiento.Entity;
				if (((previousValue != value) 
							|| (this._TipoEstablecimiento.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TipoEstablecimiento.Entity = null;
						previousValue.Establecimientos.Remove(this);
					}
					this._TipoEstablecimiento.Entity = value;
					if ((value != null))
					{
						value.Establecimientos.Add(this);
						this._idTipoEstablecimiento = value.idTipoEstablecimiento;
					}
					else
					{
						this._idTipoEstablecimiento = default(int);
					}
					this.SendPropertyChanged("TipoEstablecimiento");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Envios(Envio entity)
		{
			this.SendPropertyChanging();
			entity.Establecimiento = this;
		}
		
		private void detach_Envios(Envio entity)
		{
			this.SendPropertyChanging();
			entity.Establecimiento = null;
		}
		
		private void attach_Tarjetas(Tarjeta entity)
		{
			this.SendPropertyChanging();
			entity.Establecimiento = this;
		}
		
		private void detach_Tarjetas(Tarjeta entity)
		{
			this.SendPropertyChanging();
			entity.Establecimiento = null;
		}
		
		private void attach_Recepcions(Recepcion entity)
		{
			this.SendPropertyChanging();
			entity.Establecimiento = this;
		}
		
		private void detach_Recepcions(Recepcion entity)
		{
			this.SendPropertyChanging();
			entity.Establecimiento = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Envio")]
	public partial class Envio : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idEnvio;
		
		private System.DateTime _FechaEnvio;
		
		private int _IDUsuarioRegistro;
		
		private int _idEstablecimiento;
		
		private string _CodigoInicial;
		
		private string _CodigoFinal;
		
		private int _Estado;
		
		private System.Nullable<bool> _TieneRecepciones;
		
		private EntitySet<Tarjeta> _Tarjetas;
		
		private EntityRef<Establecimiento> _Establecimiento;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidEnvioChanging(int value);
    partial void OnidEnvioChanged();
    partial void OnFechaEnvioChanging(System.DateTime value);
    partial void OnFechaEnvioChanged();
    partial void OnIDUsuarioRegistroChanging(int value);
    partial void OnIDUsuarioRegistroChanged();
    partial void OnidEstablecimientoChanging(int value);
    partial void OnidEstablecimientoChanged();
    partial void OnCodigoInicialChanging(string value);
    partial void OnCodigoInicialChanged();
    partial void OnCodigoFinalChanging(string value);
    partial void OnCodigoFinalChanged();
    partial void OnEstadoChanging(int value);
    partial void OnEstadoChanged();
    partial void OnTieneRecepcionesChanging(System.Nullable<bool> value);
    partial void OnTieneRecepcionesChanged();
    #endregion
		
		public Envio()
		{
			this._Tarjetas = new EntitySet<Tarjeta>(new Action<Tarjeta>(this.attach_Tarjetas), new Action<Tarjeta>(this.detach_Tarjetas));
			this._Establecimiento = default(EntityRef<Establecimiento>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idEnvio", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idEnvio
		{
			get
			{
				return this._idEnvio;
			}
			set
			{
				if ((this._idEnvio != value))
				{
					this.OnidEnvioChanging(value);
					this.SendPropertyChanging();
					this._idEnvio = value;
					this.SendPropertyChanged("idEnvio");
					this.OnidEnvioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaEnvio", DbType="DateTime2 NOT NULL")]
		public System.DateTime FechaEnvio
		{
			get
			{
				return this._FechaEnvio;
			}
			set
			{
				if ((this._FechaEnvio != value))
				{
					this.OnFechaEnvioChanging(value);
					this.SendPropertyChanging();
					this._FechaEnvio = value;
					this.SendPropertyChanged("FechaEnvio");
					this.OnFechaEnvioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDUsuarioRegistro", DbType="Int NOT NULL")]
		public int IDUsuarioRegistro
		{
			get
			{
				return this._IDUsuarioRegistro;
			}
			set
			{
				if ((this._IDUsuarioRegistro != value))
				{
					this.OnIDUsuarioRegistroChanging(value);
					this.SendPropertyChanging();
					this._IDUsuarioRegistro = value;
					this.SendPropertyChanged("IDUsuarioRegistro");
					this.OnIDUsuarioRegistroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idEstablecimiento", DbType="Int NOT NULL")]
		public int idEstablecimiento
		{
			get
			{
				return this._idEstablecimiento;
			}
			set
			{
				if ((this._idEstablecimiento != value))
				{
					if (this._Establecimiento.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidEstablecimientoChanging(value);
					this.SendPropertyChanging();
					this._idEstablecimiento = value;
					this.SendPropertyChanged("idEstablecimiento");
					this.OnidEstablecimientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoInicial", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string CodigoInicial
		{
			get
			{
				return this._CodigoInicial;
			}
			set
			{
				if ((this._CodigoInicial != value))
				{
					this.OnCodigoInicialChanging(value);
					this.SendPropertyChanging();
					this._CodigoInicial = value;
					this.SendPropertyChanged("CodigoInicial");
					this.OnCodigoInicialChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoFinal", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string CodigoFinal
		{
			get
			{
				return this._CodigoFinal;
			}
			set
			{
				if ((this._CodigoFinal != value))
				{
					this.OnCodigoFinalChanging(value);
					this.SendPropertyChanging();
					this._CodigoFinal = value;
					this.SendPropertyChanged("CodigoFinal");
					this.OnCodigoFinalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="Int NOT NULL")]
		public int Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this.OnEstadoChanging(value);
					this.SendPropertyChanging();
					this._Estado = value;
					this.SendPropertyChanged("Estado");
					this.OnEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TieneRecepciones", DbType="Bit")]
		public System.Nullable<bool> TieneRecepciones
		{
			get
			{
				return this._TieneRecepciones;
			}
			set
			{
				if ((this._TieneRecepciones != value))
				{
					this.OnTieneRecepcionesChanging(value);
					this.SendPropertyChanging();
					this._TieneRecepciones = value;
					this.SendPropertyChanged("TieneRecepciones");
					this.OnTieneRecepcionesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Envio_Tarjeta", Storage="_Tarjetas", ThisKey="idEnvio", OtherKey="idEnvio")]
		public EntitySet<Tarjeta> Tarjetas
		{
			get
			{
				return this._Tarjetas;
			}
			set
			{
				this._Tarjetas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Establecimiento_Envio", Storage="_Establecimiento", ThisKey="idEstablecimiento", OtherKey="idEstablecimiento", IsForeignKey=true)]
		public Establecimiento Establecimiento
		{
			get
			{
				return this._Establecimiento.Entity;
			}
			set
			{
				Establecimiento previousValue = this._Establecimiento.Entity;
				if (((previousValue != value) 
							|| (this._Establecimiento.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Establecimiento.Entity = null;
						previousValue.Envios.Remove(this);
					}
					this._Establecimiento.Entity = value;
					if ((value != null))
					{
						value.Envios.Add(this);
						this._idEstablecimiento = value.idEstablecimiento;
					}
					else
					{
						this._idEstablecimiento = default(int);
					}
					this.SendPropertyChanged("Establecimiento");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Tarjetas(Tarjeta entity)
		{
			this.SendPropertyChanging();
			entity.Envio = this;
		}
		
		private void detach_Tarjetas(Tarjeta entity)
		{
			this.SendPropertyChanging();
			entity.Envio = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tarjeta")]
	public partial class Tarjeta : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idTarjeta;
		
		private System.Nullable<bool> _Recibido;
		
		private System.Nullable<int> _NumResultados;
		
		private System.Nullable<int> _idEnvio;
		
		private System.Nullable<int> _idRecepcion;
		
		private System.Nullable<bool> _Rechazado;
		
		private string _CodigoMuestra;
		
		private System.Nullable<int> _idEstablecimiento;
		
		private int _Estado;
		
		private EntityRef<Envio> _Envio;
		
		private EntityRef<Establecimiento> _Establecimiento;
		
		private EntityRef<Recepcion> _Recepcion;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidTarjetaChanging(int value);
    partial void OnidTarjetaChanged();
    partial void OnRecibidoChanging(System.Nullable<bool> value);
    partial void OnRecibidoChanged();
    partial void OnNumResultadosChanging(System.Nullable<int> value);
    partial void OnNumResultadosChanged();
    partial void OnidEnvioChanging(System.Nullable<int> value);
    partial void OnidEnvioChanged();
    partial void OnidRecepcionChanging(System.Nullable<int> value);
    partial void OnidRecepcionChanged();
    partial void OnRechazadoChanging(System.Nullable<bool> value);
    partial void OnRechazadoChanged();
    partial void OnCodigoMuestraChanging(string value);
    partial void OnCodigoMuestraChanged();
    partial void OnidEstablecimientoChanging(System.Nullable<int> value);
    partial void OnidEstablecimientoChanged();
    partial void OnEstadoChanging(int value);
    partial void OnEstadoChanged();
    #endregion
		
		public Tarjeta()
		{
			this._Envio = default(EntityRef<Envio>);
			this._Establecimiento = default(EntityRef<Establecimiento>);
			this._Recepcion = default(EntityRef<Recepcion>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idTarjeta", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idTarjeta
		{
			get
			{
				return this._idTarjeta;
			}
			set
			{
				if ((this._idTarjeta != value))
				{
					this.OnidTarjetaChanging(value);
					this.SendPropertyChanging();
					this._idTarjeta = value;
					this.SendPropertyChanged("idTarjeta");
					this.OnidTarjetaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Recibido", DbType="Bit")]
		public System.Nullable<bool> Recibido
		{
			get
			{
				return this._Recibido;
			}
			set
			{
				if ((this._Recibido != value))
				{
					this.OnRecibidoChanging(value);
					this.SendPropertyChanging();
					this._Recibido = value;
					this.SendPropertyChanged("Recibido");
					this.OnRecibidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumResultados", DbType="Int")]
		public System.Nullable<int> NumResultados
		{
			get
			{
				return this._NumResultados;
			}
			set
			{
				if ((this._NumResultados != value))
				{
					this.OnNumResultadosChanging(value);
					this.SendPropertyChanging();
					this._NumResultados = value;
					this.SendPropertyChanged("NumResultados");
					this.OnNumResultadosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idEnvio", DbType="Int")]
		public System.Nullable<int> idEnvio
		{
			get
			{
				return this._idEnvio;
			}
			set
			{
				if ((this._idEnvio != value))
				{
					if (this._Envio.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidEnvioChanging(value);
					this.SendPropertyChanging();
					this._idEnvio = value;
					this.SendPropertyChanged("idEnvio");
					this.OnidEnvioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idRecepcion", DbType="Int")]
		public System.Nullable<int> idRecepcion
		{
			get
			{
				return this._idRecepcion;
			}
			set
			{
				if ((this._idRecepcion != value))
				{
					if (this._Recepcion.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidRecepcionChanging(value);
					this.SendPropertyChanging();
					this._idRecepcion = value;
					this.SendPropertyChanged("idRecepcion");
					this.OnidRecepcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rechazado", DbType="Bit")]
		public System.Nullable<bool> Rechazado
		{
			get
			{
				return this._Rechazado;
			}
			set
			{
				if ((this._Rechazado != value))
				{
					this.OnRechazadoChanging(value);
					this.SendPropertyChanging();
					this._Rechazado = value;
					this.SendPropertyChanged("Rechazado");
					this.OnRechazadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoMuestra", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string CodigoMuestra
		{
			get
			{
				return this._CodigoMuestra;
			}
			set
			{
				if ((this._CodigoMuestra != value))
				{
					this.OnCodigoMuestraChanging(value);
					this.SendPropertyChanging();
					this._CodigoMuestra = value;
					this.SendPropertyChanged("CodigoMuestra");
					this.OnCodigoMuestraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idEstablecimiento", DbType="Int")]
		public System.Nullable<int> idEstablecimiento
		{
			get
			{
				return this._idEstablecimiento;
			}
			set
			{
				if ((this._idEstablecimiento != value))
				{
					if (this._Establecimiento.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidEstablecimientoChanging(value);
					this.SendPropertyChanging();
					this._idEstablecimiento = value;
					this.SendPropertyChanged("idEstablecimiento");
					this.OnidEstablecimientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="Int NOT NULL")]
		public int Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this.OnEstadoChanging(value);
					this.SendPropertyChanging();
					this._Estado = value;
					this.SendPropertyChanged("Estado");
					this.OnEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Envio_Tarjeta", Storage="_Envio", ThisKey="idEnvio", OtherKey="idEnvio", IsForeignKey=true)]
		public Envio Envio
		{
			get
			{
				return this._Envio.Entity;
			}
			set
			{
				Envio previousValue = this._Envio.Entity;
				if (((previousValue != value) 
							|| (this._Envio.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Envio.Entity = null;
						previousValue.Tarjetas.Remove(this);
					}
					this._Envio.Entity = value;
					if ((value != null))
					{
						value.Tarjetas.Add(this);
						this._idEnvio = value.idEnvio;
					}
					else
					{
						this._idEnvio = default(Nullable<int>);
					}
					this.SendPropertyChanged("Envio");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Establecimiento_Tarjeta", Storage="_Establecimiento", ThisKey="idEstablecimiento", OtherKey="idEstablecimiento", IsForeignKey=true)]
		public Establecimiento Establecimiento
		{
			get
			{
				return this._Establecimiento.Entity;
			}
			set
			{
				Establecimiento previousValue = this._Establecimiento.Entity;
				if (((previousValue != value) 
							|| (this._Establecimiento.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Establecimiento.Entity = null;
						previousValue.Tarjetas.Remove(this);
					}
					this._Establecimiento.Entity = value;
					if ((value != null))
					{
						value.Tarjetas.Add(this);
						this._idEstablecimiento = value.idEstablecimiento;
					}
					else
					{
						this._idEstablecimiento = default(Nullable<int>);
					}
					this.SendPropertyChanged("Establecimiento");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Recepcion_Tarjeta", Storage="_Recepcion", ThisKey="idRecepcion", OtherKey="idRecepcion", IsForeignKey=true)]
		public Recepcion Recepcion
		{
			get
			{
				return this._Recepcion.Entity;
			}
			set
			{
				Recepcion previousValue = this._Recepcion.Entity;
				if (((previousValue != value) 
							|| (this._Recepcion.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Recepcion.Entity = null;
						previousValue.Tarjetas.Remove(this);
					}
					this._Recepcion.Entity = value;
					if ((value != null))
					{
						value.Tarjetas.Add(this);
						this._idRecepcion = value.idRecepcion;
					}
					else
					{
						this._idRecepcion = default(Nullable<int>);
					}
					this.SendPropertyChanged("Recepcion");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Ubigeo")]
	public partial class Ubigeo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idUbigeo;
		
		private System.Nullable<int> _CodDepartamento;
		
		private System.Nullable<int> _CodProvincia;
		
		private System.Nullable<int> _CodDistrito;
		
		private string _Nombre;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidUbigeoChanging(int value);
    partial void OnidUbigeoChanged();
    partial void OnCodDepartamentoChanging(System.Nullable<int> value);
    partial void OnCodDepartamentoChanged();
    partial void OnCodProvinciaChanging(System.Nullable<int> value);
    partial void OnCodProvinciaChanged();
    partial void OnCodDistritoChanging(System.Nullable<int> value);
    partial void OnCodDistritoChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    #endregion
		
		public Ubigeo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idUbigeo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idUbigeo
		{
			get
			{
				return this._idUbigeo;
			}
			set
			{
				if ((this._idUbigeo != value))
				{
					this.OnidUbigeoChanging(value);
					this.SendPropertyChanging();
					this._idUbigeo = value;
					this.SendPropertyChanged("idUbigeo");
					this.OnidUbigeoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodDepartamento", DbType="Int")]
		public System.Nullable<int> CodDepartamento
		{
			get
			{
				return this._CodDepartamento;
			}
			set
			{
				if ((this._CodDepartamento != value))
				{
					this.OnCodDepartamentoChanging(value);
					this.SendPropertyChanging();
					this._CodDepartamento = value;
					this.SendPropertyChanged("CodDepartamento");
					this.OnCodDepartamentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodProvincia", DbType="Int")]
		public System.Nullable<int> CodProvincia
		{
			get
			{
				return this._CodProvincia;
			}
			set
			{
				if ((this._CodProvincia != value))
				{
					this.OnCodProvinciaChanging(value);
					this.SendPropertyChanging();
					this._CodProvincia = value;
					this.SendPropertyChanged("CodProvincia");
					this.OnCodProvinciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodDistrito", DbType="Int")]
		public System.Nullable<int> CodDistrito
		{
			get
			{
				return this._CodDistrito;
			}
			set
			{
				if ((this._CodDistrito != value))
				{
					this.OnCodDistritoChanging(value);
					this.SendPropertyChanging();
					this._CodDistrito = value;
					this.SendPropertyChanged("CodDistrito");
					this.OnCodDistritoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NVarChar(40)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Recepcion")]
	public partial class Recepcion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idRecepcion;
		
		private System.DateTime _FechaRecepcion;
		
		private int _IDUsuarioRegistro;
		
		private int _idEstablecimiento;
		
		private int _Estado;
		
		private EntitySet<Tarjeta> _Tarjetas;
		
		private EntityRef<Establecimiento> _Establecimiento;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidRecepcionChanging(int value);
    partial void OnidRecepcionChanged();
    partial void OnFechaRecepcionChanging(System.DateTime value);
    partial void OnFechaRecepcionChanged();
    partial void OnIDUsuarioRegistroChanging(int value);
    partial void OnIDUsuarioRegistroChanged();
    partial void OnidEstablecimientoChanging(int value);
    partial void OnidEstablecimientoChanged();
    partial void OnEstadoChanging(int value);
    partial void OnEstadoChanged();
    #endregion
		
		public Recepcion()
		{
			this._Tarjetas = new EntitySet<Tarjeta>(new Action<Tarjeta>(this.attach_Tarjetas), new Action<Tarjeta>(this.detach_Tarjetas));
			this._Establecimiento = default(EntityRef<Establecimiento>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idRecepcion", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idRecepcion
		{
			get
			{
				return this._idRecepcion;
			}
			set
			{
				if ((this._idRecepcion != value))
				{
					this.OnidRecepcionChanging(value);
					this.SendPropertyChanging();
					this._idRecepcion = value;
					this.SendPropertyChanged("idRecepcion");
					this.OnidRecepcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaRecepcion", DbType="DateTime2 NOT NULL")]
		public System.DateTime FechaRecepcion
		{
			get
			{
				return this._FechaRecepcion;
			}
			set
			{
				if ((this._FechaRecepcion != value))
				{
					this.OnFechaRecepcionChanging(value);
					this.SendPropertyChanging();
					this._FechaRecepcion = value;
					this.SendPropertyChanged("FechaRecepcion");
					this.OnFechaRecepcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDUsuarioRegistro", DbType="Int NOT NULL")]
		public int IDUsuarioRegistro
		{
			get
			{
				return this._IDUsuarioRegistro;
			}
			set
			{
				if ((this._IDUsuarioRegistro != value))
				{
					this.OnIDUsuarioRegistroChanging(value);
					this.SendPropertyChanging();
					this._IDUsuarioRegistro = value;
					this.SendPropertyChanged("IDUsuarioRegistro");
					this.OnIDUsuarioRegistroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idEstablecimiento", DbType="Int NOT NULL")]
		public int idEstablecimiento
		{
			get
			{
				return this._idEstablecimiento;
			}
			set
			{
				if ((this._idEstablecimiento != value))
				{
					if (this._Establecimiento.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidEstablecimientoChanging(value);
					this.SendPropertyChanging();
					this._idEstablecimiento = value;
					this.SendPropertyChanged("idEstablecimiento");
					this.OnidEstablecimientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="Int NOT NULL")]
		public int Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this.OnEstadoChanging(value);
					this.SendPropertyChanging();
					this._Estado = value;
					this.SendPropertyChanged("Estado");
					this.OnEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Recepcion_Tarjeta", Storage="_Tarjetas", ThisKey="idRecepcion", OtherKey="idRecepcion")]
		public EntitySet<Tarjeta> Tarjetas
		{
			get
			{
				return this._Tarjetas;
			}
			set
			{
				this._Tarjetas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Establecimiento_Recepcion", Storage="_Establecimiento", ThisKey="idEstablecimiento", OtherKey="idEstablecimiento", IsForeignKey=true)]
		public Establecimiento Establecimiento
		{
			get
			{
				return this._Establecimiento.Entity;
			}
			set
			{
				Establecimiento previousValue = this._Establecimiento.Entity;
				if (((previousValue != value) 
							|| (this._Establecimiento.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Establecimiento.Entity = null;
						previousValue.Recepcions.Remove(this);
					}
					this._Establecimiento.Entity = value;
					if ((value != null))
					{
						value.Recepcions.Add(this);
						this._idEstablecimiento = value.idEstablecimiento;
					}
					else
					{
						this._idEstablecimiento = default(int);
					}
					this.SendPropertyChanged("Establecimiento");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Tarjetas(Tarjeta entity)
		{
			this.SendPropertyChanging();
			entity.Recepcion = this;
		}
		
		private void detach_Tarjetas(Tarjeta entity)
		{
			this.SendPropertyChanging();
			entity.Recepcion = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Rango")]
	public partial class Rango
	{
		
		private int _idRango;
		
		private string _Rango1;
		
		private System.Nullable<int> _idPrueba;
		
		private System.Nullable<int> _Estado;
		
		private System.Nullable<System.DateTime> _FechaRegistro;
		
		public Rango()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idRango", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int idRango
		{
			get
			{
				return this._idRango;
			}
			set
			{
				if ((this._idRango != value))
				{
					this._idRango = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Rango", Storage="_Rango1", DbType="NVarChar(20)")]
		public string Rango1
		{
			get
			{
				return this._Rango1;
			}
			set
			{
				if ((this._Rango1 != value))
				{
					this._Rango1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPrueba", DbType="Int")]
		public System.Nullable<int> idPrueba
		{
			get
			{
				return this._idPrueba;
			}
			set
			{
				if ((this._idPrueba != value))
				{
					this._idPrueba = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="Int")]
		public System.Nullable<int> Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaRegistro", DbType="DateTime2")]
		public System.Nullable<System.DateTime> FechaRegistro
		{
			get
			{
				return this._FechaRegistro;
			}
			set
			{
				if ((this._FechaRegistro != value))
				{
					this._FechaRegistro = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Prueba")]
	public partial class Prueba : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idPrueba;
		
		private string _Nombre;
		
		private string _NombreCorto;
		
		private string _Metodo;
		
		private int _Estado;
		
		private string _Unidad;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidPruebaChanging(int value);
    partial void OnidPruebaChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnNombreCortoChanging(string value);
    partial void OnNombreCortoChanged();
    partial void OnMetodoChanging(string value);
    partial void OnMetodoChanged();
    partial void OnEstadoChanging(int value);
    partial void OnEstadoChanged();
    partial void OnUnidadChanging(string value);
    partial void OnUnidadChanged();
    #endregion
		
		public Prueba()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPrueba", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idPrueba
		{
			get
			{
				return this._idPrueba;
			}
			set
			{
				if ((this._idPrueba != value))
				{
					this.OnidPruebaChanging(value);
					this.SendPropertyChanging();
					this._idPrueba = value;
					this.SendPropertyChanged("idPrueba");
					this.OnidPruebaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreCorto", DbType="NVarChar(12) NOT NULL", CanBeNull=false)]
		public string NombreCorto
		{
			get
			{
				return this._NombreCorto;
			}
			set
			{
				if ((this._NombreCorto != value))
				{
					this.OnNombreCortoChanging(value);
					this.SendPropertyChanging();
					this._NombreCorto = value;
					this.SendPropertyChanged("NombreCorto");
					this.OnNombreCortoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Metodo", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Metodo
		{
			get
			{
				return this._Metodo;
			}
			set
			{
				if ((this._Metodo != value))
				{
					this.OnMetodoChanging(value);
					this.SendPropertyChanging();
					this._Metodo = value;
					this.SendPropertyChanged("Metodo");
					this.OnMetodoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="Int NOT NULL")]
		public int Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this.OnEstadoChanging(value);
					this.SendPropertyChanging();
					this._Estado = value;
					this.SendPropertyChanged("Estado");
					this.OnEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Unidad", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string Unidad
		{
			get
			{
				return this._Unidad;
			}
			set
			{
				if ((this._Unidad != value))
				{
					this.OnUnidadChanging(value);
					this.SendPropertyChanging();
					this._Unidad = value;
					this.SendPropertyChanged("Unidad");
					this.OnUnidadChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Vista_ListaTarjetas")]
	public partial class Vista_ListaTarjeta
	{
		
		private string _CodigoMuestra;
		
		private System.Nullable<bool> _Rechazado;
		
		private System.Nullable<bool> _Recibido;
		
		private System.Nullable<System.DateTime> _FechaEnvio;
		
		private System.Nullable<System.DateTime> _FechaRecepcion;
		
		private int _idEnvio;
		
		private int _idTarjeta;
		
		private System.Nullable<int> _idRecepcion;
		
		public Vista_ListaTarjeta()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoMuestra", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string CodigoMuestra
		{
			get
			{
				return this._CodigoMuestra;
			}
			set
			{
				if ((this._CodigoMuestra != value))
				{
					this._CodigoMuestra = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rechazado", DbType="Bit")]
		public System.Nullable<bool> Rechazado
		{
			get
			{
				return this._Rechazado;
			}
			set
			{
				if ((this._Rechazado != value))
				{
					this._Rechazado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Recibido", DbType="Bit")]
		public System.Nullable<bool> Recibido
		{
			get
			{
				return this._Recibido;
			}
			set
			{
				if ((this._Recibido != value))
				{
					this._Recibido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaEnvio", DbType="DateTime2")]
		public System.Nullable<System.DateTime> FechaEnvio
		{
			get
			{
				return this._FechaEnvio;
			}
			set
			{
				if ((this._FechaEnvio != value))
				{
					this._FechaEnvio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaRecepcion", DbType="DateTime2")]
		public System.Nullable<System.DateTime> FechaRecepcion
		{
			get
			{
				return this._FechaRecepcion;
			}
			set
			{
				if ((this._FechaRecepcion != value))
				{
					this._FechaRecepcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idEnvio", DbType="Int NOT NULL")]
		public int idEnvio
		{
			get
			{
				return this._idEnvio;
			}
			set
			{
				if ((this._idEnvio != value))
				{
					this._idEnvio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idTarjeta", DbType="Int NOT NULL")]
		public int idTarjeta
		{
			get
			{
				return this._idTarjeta;
			}
			set
			{
				if ((this._idTarjeta != value))
				{
					this._idTarjeta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idRecepcion", DbType="Int")]
		public System.Nullable<int> idRecepcion
		{
			get
			{
				return this._idRecepcion;
			}
			set
			{
				if ((this._idRecepcion != value))
				{
					this._idRecepcion = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Vista_ListaRecepciones")]
	public partial class Vista_ListaRecepcione
	{
		
		private int _idRecepcion;
		
		private System.DateTime _FechaRecepcion;
		
		private int _idEstablecimiento;
		
		private string _Establecimiento;
		
		private int _idTipoEstablecimiento;
		
		private string _TipoEstablecimiento;
		
		private int _Estado;
		
		public Vista_ListaRecepcione()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idRecepcion", DbType="Int NOT NULL")]
		public int idRecepcion
		{
			get
			{
				return this._idRecepcion;
			}
			set
			{
				if ((this._idRecepcion != value))
				{
					this._idRecepcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaRecepcion", DbType="DateTime2 NOT NULL")]
		public System.DateTime FechaRecepcion
		{
			get
			{
				return this._FechaRecepcion;
			}
			set
			{
				if ((this._FechaRecepcion != value))
				{
					this._FechaRecepcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idEstablecimiento", DbType="Int NOT NULL")]
		public int idEstablecimiento
		{
			get
			{
				return this._idEstablecimiento;
			}
			set
			{
				if ((this._idEstablecimiento != value))
				{
					this._idEstablecimiento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Establecimiento", DbType="NVarChar(64)")]
		public string Establecimiento
		{
			get
			{
				return this._Establecimiento;
			}
			set
			{
				if ((this._Establecimiento != value))
				{
					this._Establecimiento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idTipoEstablecimiento", DbType="Int NOT NULL")]
		public int idTipoEstablecimiento
		{
			get
			{
				return this._idTipoEstablecimiento;
			}
			set
			{
				if ((this._idTipoEstablecimiento != value))
				{
					this._idTipoEstablecimiento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoEstablecimiento", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TipoEstablecimiento
		{
			get
			{
				return this._TipoEstablecimiento;
			}
			set
			{
				if ((this._TipoEstablecimiento != value))
				{
					this._TipoEstablecimiento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="Int NOT NULL")]
		public int Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Vista_ListaEnvios")]
	public partial class Vista_ListaEnvio
	{
		
		private int _idEnvio;
		
		private System.DateTime _FechaEnvio;
		
		private int _idEstablecimiento;
		
		private string _Establecimiento;
		
		private string _CodigoInicial;
		
		private string _CodigoFinal;
		
		private int _idTipoEstablecimiento;
		
		private string _TipoEstablecimiento;
		
		private System.Nullable<bool> _TieneRecepciones;
		
		private int _Estado;
		
		public Vista_ListaEnvio()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idEnvio", DbType="Int NOT NULL")]
		public int idEnvio
		{
			get
			{
				return this._idEnvio;
			}
			set
			{
				if ((this._idEnvio != value))
				{
					this._idEnvio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaEnvio", DbType="DateTime2 NOT NULL")]
		public System.DateTime FechaEnvio
		{
			get
			{
				return this._FechaEnvio;
			}
			set
			{
				if ((this._FechaEnvio != value))
				{
					this._FechaEnvio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idEstablecimiento", DbType="Int NOT NULL")]
		public int idEstablecimiento
		{
			get
			{
				return this._idEstablecimiento;
			}
			set
			{
				if ((this._idEstablecimiento != value))
				{
					this._idEstablecimiento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Establecimiento", DbType="NVarChar(64)")]
		public string Establecimiento
		{
			get
			{
				return this._Establecimiento;
			}
			set
			{
				if ((this._Establecimiento != value))
				{
					this._Establecimiento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoInicial", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string CodigoInicial
		{
			get
			{
				return this._CodigoInicial;
			}
			set
			{
				if ((this._CodigoInicial != value))
				{
					this._CodigoInicial = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoFinal", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string CodigoFinal
		{
			get
			{
				return this._CodigoFinal;
			}
			set
			{
				if ((this._CodigoFinal != value))
				{
					this._CodigoFinal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idTipoEstablecimiento", DbType="Int NOT NULL")]
		public int idTipoEstablecimiento
		{
			get
			{
				return this._idTipoEstablecimiento;
			}
			set
			{
				if ((this._idTipoEstablecimiento != value))
				{
					this._idTipoEstablecimiento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoEstablecimiento", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TipoEstablecimiento
		{
			get
			{
				return this._TipoEstablecimiento;
			}
			set
			{
				if ((this._TipoEstablecimiento != value))
				{
					this._TipoEstablecimiento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TieneRecepciones", DbType="Bit")]
		public System.Nullable<bool> TieneRecepciones
		{
			get
			{
				return this._TieneRecepciones;
			}
			set
			{
				if ((this._TieneRecepciones != value))
				{
					this._TieneRecepciones = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="Int NOT NULL")]
		public int Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Vista_Establecimientos")]
	public partial class Vista_Establecimiento
	{
		
		private int _idEstablecimiento;
		
		private string _Codigo;
		
		private int _idTipoEstablecimiento;
		
		private string _Establecimiento;
		
		private string _TipoEstablecimiento;
		
		private string _Direccion;
		
		private string _Telefono1;
		
		private string _Telefono2;
		
		private System.Nullable<int> _depUbigeo;
		
		private System.Nullable<int> _proUbigeo;
		
		private System.Nullable<int> _disUbigeo;
		
		private string _Departamento;
		
		private string _Provincia;
		
		private string _Distrito;
		
		public Vista_Establecimiento()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idEstablecimiento", DbType="Int NOT NULL")]
		public int idEstablecimiento
		{
			get
			{
				return this._idEstablecimiento;
			}
			set
			{
				if ((this._idEstablecimiento != value))
				{
					this._idEstablecimiento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Codigo", DbType="NVarChar(32)")]
		public string Codigo
		{
			get
			{
				return this._Codigo;
			}
			set
			{
				if ((this._Codigo != value))
				{
					this._Codigo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idTipoEstablecimiento", DbType="Int NOT NULL")]
		public int idTipoEstablecimiento
		{
			get
			{
				return this._idTipoEstablecimiento;
			}
			set
			{
				if ((this._idTipoEstablecimiento != value))
				{
					this._idTipoEstablecimiento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Establecimiento", DbType="NVarChar(64)")]
		public string Establecimiento
		{
			get
			{
				return this._Establecimiento;
			}
			set
			{
				if ((this._Establecimiento != value))
				{
					this._Establecimiento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoEstablecimiento", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TipoEstablecimiento
		{
			get
			{
				return this._TipoEstablecimiento;
			}
			set
			{
				if ((this._TipoEstablecimiento != value))
				{
					this._TipoEstablecimiento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="NVarChar(40)")]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this._Direccion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono1", DbType="NVarChar(15)")]
		public string Telefono1
		{
			get
			{
				return this._Telefono1;
			}
			set
			{
				if ((this._Telefono1 != value))
				{
					this._Telefono1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono2", DbType="NVarChar(15)")]
		public string Telefono2
		{
			get
			{
				return this._Telefono2;
			}
			set
			{
				if ((this._Telefono2 != value))
				{
					this._Telefono2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_depUbigeo", DbType="Int")]
		public System.Nullable<int> depUbigeo
		{
			get
			{
				return this._depUbigeo;
			}
			set
			{
				if ((this._depUbigeo != value))
				{
					this._depUbigeo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_proUbigeo", DbType="Int")]
		public System.Nullable<int> proUbigeo
		{
			get
			{
				return this._proUbigeo;
			}
			set
			{
				if ((this._proUbigeo != value))
				{
					this._proUbigeo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_disUbigeo", DbType="Int")]
		public System.Nullable<int> disUbigeo
		{
			get
			{
				return this._disUbigeo;
			}
			set
			{
				if ((this._disUbigeo != value))
				{
					this._disUbigeo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Departamento", DbType="NVarChar(40)")]
		public string Departamento
		{
			get
			{
				return this._Departamento;
			}
			set
			{
				if ((this._Departamento != value))
				{
					this._Departamento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Provincia", DbType="NVarChar(40)")]
		public string Provincia
		{
			get
			{
				return this._Provincia;
			}
			set
			{
				if ((this._Provincia != value))
				{
					this._Provincia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Distrito", DbType="NVarChar(40)")]
		public string Distrito
		{
			get
			{
				return this._Distrito;
			}
			set
			{
				if ((this._Distrito != value))
				{
					this._Distrito = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
